name: Auto Update Bot

on:
  schedule:
    - cron: "0 * * * *"   # jalan tiap 1 jam
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update data
        run: |
          echo "Update terakhir: $(date)" > auto_update.txt

      - name: Commit changes
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Auto Bot"
          git add .
          git commit -m "Auto update data"
          git push
